version: "3"

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - db.env

  api:
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DATABASE_URL=postgresql://tlqs:tlqs@db:5432/tlqs?sslmode=disable

volumes:
  db-data:
